version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: test-qdrant
    ports:
      - 6351:6333
      - 6352:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: test-database
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"